# ------------------------------------------------------------
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
# ------------------------------------------------------------

# The name of the product (or extension) being used.
product: asterixdb

# The server binary zip.
binary: asterix-server-*-binary-assembly.zip

# The script that starts a nc service.
ncsbin: "asterixncservice"

# The script that starts a nc.
ncbin: "asterixnc"

# The script that starts a cc.
ccbin: "asterixcc"

# The parent directory for the working directory.
basedir: /home/ec2-user

# The working directory.
binarydir: "{{ basedir }}/{{ product }}"

# The pattern for retrieving the sever binary zip from the current build.
srcpattern: "../../../{{ binary }}"

# The nc service command (script).
ncservice: "{{ binarydir}}/bin/{{ ncsbin }}"

# The cc service command (script).
cc: "{{ binarydir}}/bin/{{ ccbin }}"
